### ISSUE TITLE
Multi-Spawner fails if world size is too big

### ISSUE THREAD

**Issue by Mythbusters123** [Badel2/slime_seed_finder#32] opened 2022-06-27 00:41 UTC
![image](https://user-images.githubusercontent.com/58893124/175840907-1a7117b4-0de1-4a0a-8eb0-ca6a42f1ac20.png)

**Comment by Badel2** [comment] 2022-06-28 14:27
Hi, thanks for the bug report! From the screenshot I see that the world size is 668 MB. It's true that there may be some issues with large words when the WebAssembly runtime runs out of memory, but in that case you wouldn't see this error message. So this looks like a bug in the anvil-region parsing code. I was able to reproduce the issue using this map: https://www.minecraftmaps.com/city-maps/alma-bay so I will try to fix it.

**Comment by Badel2** [comment] 2022-07-01 18:54
So this is now fixed because I removed the piece of code that generates that error message. However big worlds may still cause other issues, but if you are lucky your world may work now. I opened #34 to add an error message in case in case the world is actually too big, but in theory the limit is 4GB. I you see a different error message feel free to open a new issue.

**Closed by Badel2** 2022-07-01 18:54 UTC

**Comment by Mythbusters123** [comment] 2022-07-01 23:28
Thanks so much!
